[package]
name = "c64emu"
version = "0.1.0"
authors = ["Jaakko Ketola <jaaket@kapsi.fi>"]

[dependencies]
lazy_static = "1"
regex = "1"
rustyline = "1"
sdl2 = "0.31"
bitflags = "1"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"